/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudyStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const StudyTopic = IDL.Record({
  'id' : IDL.Nat,
  'status' : StudyStatus,
  'name' : IDL.Text,
});
export const Exam = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : Time,
  'time' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
  'topics' : IDL.Vec(StudyTopic),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExam' : IDL.Func([IDL.Text, Time, IDL.Text], [IDL.Nat], []),
  'addStudyTopic' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExam' : IDL.Func([IDL.Nat], [], []),
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExam' : IDL.Func([IDL.Nat], [Exam], ['query']),
  'getExamResults' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordExamScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateExam' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Text], [], []),
  'updateTopicStatus' : IDL.Func([IDL.Nat, IDL.Nat, StudyStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudyStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const StudyTopic = IDL.Record({
    'id' : IDL.Nat,
    'status' : StudyStatus,
    'name' : IDL.Text,
  });
  const Exam = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : Time,
    'time' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
    'topics' : IDL.Vec(StudyTopic),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExam' : IDL.Func([IDL.Text, Time, IDL.Text], [IDL.Nat], []),
    'addStudyTopic' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExam' : IDL.Func([IDL.Nat], [], []),
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExam' : IDL.Func([IDL.Nat], [Exam], ['query']),
    'getExamResults' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordExamScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateExam' : IDL.Func([IDL.Nat, IDL.Text, Time, IDL.Text], [], []),
    'updateTopicStatus' : IDL.Func([IDL.Nat, IDL.Nat, StudyStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };